version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: bankapp_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - bankapp_db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - bankapp_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bankapp_backend
    restart: always
    environment:
      PORT: ${BACKEND_PORT}
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - mysql
    # volumes:
      # - ./backend:/usr/src/app
    networks:
      - bankapp_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bankapp_frontend
    restart: always
    environment:
      REACT_APP_API_URL: http://localhost:${BACKEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    # volumes:
      # - ./frontend:/usr/src/app
    networks:
      - bankapp_network

networks:
  bankapp_network:

volumes:
  bankapp_db_data:
